### ISSUE TITLE
Vmware pro version 16.x 

### ISSUE THREAD

**Issue by akshada-24** [Hrishikesh-K/WinHackerman#337]
I am using windows 10 operating system.
I have installed VMware 16 version. But after installation it is not adding virtual drivers (VMnet1, VMnet8). 
[file.docx](https://github.com/Hrishikesh-K/WinHackerman/files/5350557/file.docx)

**Comment by Hrishikesh-K** [comment]
Thank you for contacting us.

About the issue, it's strange. However, it's not really an issue from our end. At best, we could help you by pointing to an online link that discusses the same issue. Would you mind trying it out and posting if it works?

Here's what a quick Google search returned: https://superuser.com/questions/948408/vmware-workstation-not-installing-network-adapters-on-windows-10

**Comment by akshada-24** [comment]
Thank you for this solution.

Earlier, when I wanted to install VMware, and when the installation was complete, the adapters were also disappearing. 
When I installed according to the solution you gave then the adapters are visible after installation. But are disabled.
I have attached the file which has a screenshot. Please see it.

Thank you for your time.
[file1.docx](https://github.com/Hrishikesh-K/WinHackerman/files/5354556/file1.docx)

**Comment by Hrishikesh-K** [comment]
@akshada-24 Did you try manually enabling the adapters? If yes, did you get any error?

**Comment by akshada-24** [comment]
@Hrishikesh-K  I have not manually enabled the adapters. When the installation was complete I tried to update those adapters but the drivers were not updated and not enabled either.

**Comment by Hrishikesh-K** [comment]
Please try enabling the adapters then. If it doesn't work, we're sorry. That's the problem with the software and not with us. We can't be providing help for softwares that we haven't developed ourselves.

**Comment by akshada-24** [comment]
@Hrishikesh-K Thank you for your help! I will try.

**Comment by Hrishikesh-K** [comment]
I'm closing this issue for the time being. It will be locked after 3 days. Re-open it if needed before it gets locked.

**Comment by akshada-24** [comment]
Sure! I will let you know in these three days.

Thank you!
